platform: linux
image_resource:
  type: docker-image
  source:
    repository: making/alpine-java-bash-git
inputs:
  - name: repo
  - name: repo-ci
  - name: utils
  - name: m2
run:
  path: sh
  args:
  - -c
  - |
    utils/scripts/add-repos-in-pom-xml.sh repo && \
    repo-ci/ci/tasks/unit.sh repo
params:
  _JAVA_OPTIONS: -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP -Djava.security.egd=file:/dev/./urandom